### ISSUE TITLE
Research possible stats to use in uncovering unknown but interesting FOSS projects

### ISSUE THREAD

**Issue by mvdkleijn** [mvdkleijn/fosstats#4]

**Comment by mvdkleijn** [comment]
@wilkie @Daxter This is a continuation from https://github.com/gittip/www.gittip.com/issues/881#issuecomment-24414500

**Comment by mvdkleijn** [comment]
From @wilkie:

> Create some heuristic that indicates both "active" and "interesting" yet "overlooked" ... I have no idea, but to brainstorm, maybe: number of commits per day multiplied by number of contributors divided by number of stars. That would weigh active projects with more people, yet little notoriety, well. (This would be a great one-off website idea on its own)

**Comment by mvdkleijn** [comment]
from @mvdkleijn:

> You could also decide to list projects with few developers, but a long history. The ’loner’ project as it were. I'm sure we can think of other metrics too. Maybe make a separate issue for it?

**Comment by seanlinsley** [comment]
I assume you're planning on using http://www.githubarchive.org/?

**Comment by mvdkleijn** [comment]
Forgot to list that, but yes. The normal API can be used as a fallback or if we're making project profiles. (though that'd be awfully Ohloh-ish)

**Comment by mvdkleijn** [comment]
@Daxter Glad to see you here by the way. :smiley:
